### ISSUE TITLE
Define outreach activities

### ISSUE THREAD

**Issue by semuelle** [PolkadotOpenSourceGrants/.github#3]

**Comment by Tomen** [comment]
Get our links placed in the following portals:
- LilyMendz
- OpenGovWatch page
- Subsquare
- Polkassembly
- Polkadot Wiki
- dot-awesome

Announcement campaign for inputs
- Social Media Posts for Twitter & Reddit
  - Retweets through official accounts
- promote to PBA
- YouTube Live at Polkadot YouTube?
- ask W3F for further outreach
